FROM golang:1.18-alpine3.17 AS build-container

RUN apk add git && git clone https://github.com/btcsuite/btcd /app

WORKDIR /app 
RUN GOARCH=amd64 go install -v . ./cmd/*

FROM amd64/alpine:3.16

COPY --from=build-container /go/bin/**/* /bin

VOLUME ["/root/.btcd"]

EXPOSE 18333 18334

ENTRYPOINT ["btcd"]
