version: '3.8'

services:
  btcsuite:
    container_name: btcsuite
    hostname: btcsuite
    build: 
      context: .
      dockerfile: Dockerfile.btcsuite
    restart: unless-stopped
    volumes:
      - btcd-data:/root/.btcd
      - btcwallet-data:/root/.btcwallet 
      - ./btcd.conf:/root/.btcd/btcd.conf 
      - ./btcwallet.conf:/root/.btcwallet/btcwallet.conf 
      - ./btcctl.conf:/root/.btcctl/btcctl.conf 
    ports:
      - 18554:18554
      - 18555:18555
      - 18556:18556

volumes:
  btcd-data:
  btcwallet-data:

